package com.wj.generate;

import java.util.Date;

public class CustomerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.c_id
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.c_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.c_address
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String cAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.contact_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.contact_phone
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.contact_mail
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String contactMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.sales_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String salesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.deliver_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String deliverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.taxpayer_id
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String taxpayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.opening_bank
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String openingBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.bank_account
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.is_taxfree
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Byte isTaxfree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.taxfree_amount
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Long taxfreeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.remark
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.is_customer
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Byte isCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.create_time
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.update_time
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.update_user
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.is_deleted
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.c_id
     *
     * @return the value of customer_info.c_id
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.c_id
     *
     * @param cId the value for customer_info.c_id
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.c_name
     *
     * @return the value of customer_info.c_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.c_name
     *
     * @param cName the value for customer_info.c_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.c_address
     *
     * @return the value of customer_info.c_address
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.c_address
     *
     * @param cAddress the value for customer_info.c_address
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.contact_name
     *
     * @return the value of customer_info.contact_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.contact_name
     *
     * @param contactName the value for customer_info.contact_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.contact_phone
     *
     * @return the value of customer_info.contact_phone
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.contact_phone
     *
     * @param contactPhone the value for customer_info.contact_phone
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.contact_mail
     *
     * @return the value of customer_info.contact_mail
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getContactMail() {
        return contactMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.contact_mail
     *
     * @param contactMail the value for customer_info.contact_mail
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setContactMail(String contactMail) {
        this.contactMail = contactMail == null ? null : contactMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.sales_name
     *
     * @return the value of customer_info.sales_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getSalesName() {
        return salesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.sales_name
     *
     * @param salesName the value for customer_info.sales_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setSalesName(String salesName) {
        this.salesName = salesName == null ? null : salesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.deliver_name
     *
     * @return the value of customer_info.deliver_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getDeliverName() {
        return deliverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.deliver_name
     *
     * @param deliverName the value for customer_info.deliver_name
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setDeliverName(String deliverName) {
        this.deliverName = deliverName == null ? null : deliverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.taxpayer_id
     *
     * @return the value of customer_info.taxpayer_id
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.taxpayer_id
     *
     * @param taxpayerId the value for customer_info.taxpayer_id
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId == null ? null : taxpayerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.opening_bank
     *
     * @return the value of customer_info.opening_bank
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.opening_bank
     *
     * @param openingBank the value for customer_info.opening_bank
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank == null ? null : openingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.bank_account
     *
     * @return the value of customer_info.bank_account
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.bank_account
     *
     * @param bankAccount the value for customer_info.bank_account
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.is_taxfree
     *
     * @return the value of customer_info.is_taxfree
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Byte getIsTaxfree() {
        return isTaxfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.is_taxfree
     *
     * @param isTaxfree the value for customer_info.is_taxfree
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setIsTaxfree(Byte isTaxfree) {
        this.isTaxfree = isTaxfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.taxfree_amount
     *
     * @return the value of customer_info.taxfree_amount
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Long getTaxfreeAmount() {
        return taxfreeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.taxfree_amount
     *
     * @param taxfreeAmount the value for customer_info.taxfree_amount
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setTaxfreeAmount(Long taxfreeAmount) {
        this.taxfreeAmount = taxfreeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.remark
     *
     * @return the value of customer_info.remark
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.remark
     *
     * @param remark the value for customer_info.remark
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.is_customer
     *
     * @return the value of customer_info.is_customer
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Byte getIsCustomer() {
        return isCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.is_customer
     *
     * @param isCustomer the value for customer_info.is_customer
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setIsCustomer(Byte isCustomer) {
        this.isCustomer = isCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.create_time
     *
     * @return the value of customer_info.create_time
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.create_time
     *
     * @param createTime the value for customer_info.create_time
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.update_time
     *
     * @return the value of customer_info.update_time
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.update_time
     *
     * @param updateTime the value for customer_info.update_time
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.update_user
     *
     * @return the value of customer_info.update_user
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.update_user
     *
     * @param updateUser the value for customer_info.update_user
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.is_deleted
     *
     * @return the value of customer_info.is_deleted
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.is_deleted
     *
     * @param isDeleted the value for customer_info.is_deleted
     *
     * @mbg.generated Wed Jun 03 17:05:35 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}